spring:
  application:
    name: quoraApp

  data:
    mongodb:
      host: localhost
      port: 27017
      database: quora_db
      auto-index-creation: true

  kafka: # Add this section for Kafka configuration
    bootstrap-servers: localhost:9092 # Replace with your Kafka broker address if different
    consumer:
      group-id: view-count-consumer # This matches your current groupId in KafkaConfig.java

  elasticsearch:
    urls: http:localhost:9200
logging:
  level:
    root: DEBUG                # Global log level
    org.springframework: WARN # Specific package level